dist: trusty
sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
# install dependencies
install:
  - pip install pipenv
# run tests
script:
  - pipenv install -d
  - pipenv run pytest
  - pipenv run codecov
